### ISSUE TITLE
Need to check the different between `SyncSet` and `Deployable`

### ISSUE THREAD

**Issue by gyliu513** [IBM/multicloud-operators-deployable#10]
@kuanf can you help check

Here is a document for `SyncSet` and `Deployable`? 

The `SyncSet` is a concept in Hive which is very similar with `Deployable`, here is the document https://github.com/openshift/hive/blob/master/docs/syncset.md 

A sample `SyncSet` is as follows:

```yaml
---
apiVersion: hive.openshift.io/v1alpha1
kind: SyncSet
metadata:
  name: mygroup
spec:
  clusterDeploymentRefs:
  - name: ClusterName

  resourceApplyMode: Upsert

  resources:
  - apiVersion: user.openshift.io/v1
    kind: Group
    metadata:
      name: mygroup
    users:
    - myuser

  patches:
  - kind: ConfigMap
    apiVersion: v1
    name: foo
    namespace: default
    applyMode: AlwaysApply
    patch: |-
      { "data": { "foo": "new-bar" } }
    patchType: merge
```

The `SyncSet` can not only distribute resources to different clusters, but also patch resources in different clusters.

FYI @mdelder @clyang82
